spring:
  application:
    name: Kafka sandbox web
  # See class org.springframework.boot.autoconfigure.kafka.KafkaProperties:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: spring-web
      group-id: ${GROUPID:spring-web}
      properties:
        spring.json.trusted.packages: no.nav.kafka.sandbox.messages
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest


consolemessages:
  event-store:
    max-size: 200
  consumer:
    topic: messages

measurements:
  event-store:
    # max size, older events will be discarded, unless 'fail-on-max-size' is true
    max-size: 200
    # set to true to fail instead of discarding old elements when event store is full (test Kafka error handling for a persistent error)
    fail-on-max-size: false
    # set how often store writes should fail (to test Kafka consumer error handling for errors occuring sometimes)
    failure-rate: 0.0
  consumer:
    topic: measurements
    # increase this to slow down batch consumer, which will result in getting larger batches for each call (value in milliseconds)
    slowdown: 0
    # Select error handler. Unset or 'spring-default' just uses the Spring Kafka default handling.
    # 'ignore-errors' logs, but ignores all errors from consumer, implemented in class "IgnoreErrorsHandler"
    error-handler: spring-default
