#!/bin/sh
set -e

cd "$(dirname "$0")"

if ! test -f messages/target/messages-*.jar -a -f clients/target/clients-*-exec.jar; then
    mvn -B install
fi

exec java -jar clients/target/clients-*-exec.jar "$@"
